set_input_delay -clock [get_clocks sys_clk_pin] -min -add_delay 4.000 [get_ports {X[*]}]
set_input_delay -clock [get_clocks sys_clk_pin] -max -add_delay 1.000 [get_ports {X[*]}]
set_input_delay -clock [get_clocks sys_clk_pin] -min -add_delay 4.000 [get_ports {Y[*]}]
set_input_delay -clock [get_clocks sys_clk_pin] -max -add_delay 1.000 [get_ports {Y[*]}]
set_input_delay -clock [get_clocks sys_clk_pin] -min -add_delay 4.000 [get_ports rst]
set_input_delay -clock [get_clocks sys_clk_pin] -max -add_delay 1.000 [get_ports rst]
set_input_delay -clock [get_clocks sys_clk_pin] -clock_fall -min -add_delay 4.000 [get_ports start]
set_input_delay -clock [get_clocks sys_clk_pin] -clock_fall -max -add_delay 1.000 [get_ports start]
set_output_delay -clock [get_clocks sys_clk_pin] -min -add_delay 3.000 [get_ports {res[*]}]
set_output_delay -clock [get_clocks sys_clk_pin] -max -add_delay 2.000 [get_ports {res[*]}]
